name: student-performance-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - matplotlib
      - seaborn
